import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry'
import { NavBar } from './components/Navbar'

export const metadata: Metadata = {
  title: 'Imersão 14 - Sistema de rastreabilidade de veículos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <NavBar></NavBar>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  )
}
