GET http://localhost:3000/


###
GET http://localhost:3000/routes


###
GET http://localhost:3000/routes/64e5022fcafcbf30841ec1e1


###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route teste 3",
  "source_id": "ChIJSSZVovbIyJQRNjUEWBwAdXQ",
  "destination_id": "ChIJKVnRj8POyJQRzjkarcuLLgQ"
}


# GOOGLE - Places

###
GET http://localhost:3000/places?text=campinas

###
GET http://localhost:3000/places?text=rua synira arruda valente, 718




# GOOGLE - Directions

###
GET http://localhost:3000/directions?originId=ChIJSSZVovbIyJQRNjUEWBwAdXQ&destinationId=ChIJKVnRj8POyJQRzjkarcuLLgQ
